#settings
url_base: "federal-open-source-repos"
title: "Government Open Source Projects"
description: "A dynamically generated list of open source projects hosted on GitHub.  If you hit the rate limit of GitHub's API, use this version: <a href="http://federal-repositories.herokuapp.com/">http://federal-repositories.herokuapp.com/</a>"
sm_api: "http://registry.usa.gov/accounts.json?service_id=github&callback=?"
gh_api: "https://api.github.com/users/<%= account %>/repos?callback=?"
repo: "https://github.com/GSA/federal-open-source-repos"

#build config
server: true
auto: true
exclude: ["node_modules"]

#API Keys to avoid rate limits while deving
client_id: ""
client_secret: ""
