// Generated by CoffeeScript 1.4.0
(function() {
  var router,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.RepoList = {
    Models: {},
    Collections: {},
    Views: {},
    router: {},
    agencies: {}
  };

  RepoList.Models.Agency = (function(_super) {

    __extends(Agency, _super);

    function Agency() {
      return Agency.__super__.constructor.apply(this, arguments);
    }

    return Agency;

  })(Backbone.Model);

  RepoList.Collections.Agencies = (function(_super) {

    __extends(Agencies, _super);

    function Agencies() {
      return Agencies.__super__.constructor.apply(this, arguments);
    }

    Agencies.prototype.model = RepoList.Models.Agency;

    Agencies.prototype.url = '{{ site.sm_api }}';

    Agencies.prototype.parse = function(response) {
      return response.accounts;
    };

    Agencies.prototype.initialize = function() {
      return this.on('add', this.getRepos);
    };

    Agencies.prototype.getRepos = function(model) {
      var repos;
      repos = new RepoList.Collections.Repos();
      repos.agency = model;
      model.set('repos', repos);
      return repos.fetch();
    };

    return Agencies;

  })(Backbone.Collection);

  RepoList.Models.Repo = (function(_super) {

    __extends(Repo, _super);

    function Repo() {
      return Repo.__super__.constructor.apply(this, arguments);
    }

    return Repo;

  })(Backbone.Model);

  RepoList.Collections.Repos = (function(_super) {

    __extends(Repos, _super);

    function Repos() {
      return Repos.__super__.constructor.apply(this, arguments);
    }

    Repos.prototype.model = RepoList.Models.Repo;

    Repos.prototype.agency = {};

    Repos.prototype.urlTemplate = '{{ site.gh_api }}';

    Repos.prototype.url = function() {
      var compiled;
      compiled = _.template(this.urlTemplate);
      return compiled(this.agency.toJSON());
    };

    Repos.prototype.parse = function(response) {
      return response.data;
    };

    return Repos;

  })(Backbone.Collection);

  RepoList.Views.Index = (function(_super) {

    __extends(Index, _super);

    function Index() {
      this.render = __bind(this.render, this);
      return Index.__super__.constructor.apply(this, arguments);
    }

    Index.prototype.el = "#repo-list";

    Index.prototype.tagName = "li";

    Index.prototype["class"] = "repo";

    Index.prototype.template = $('#index_template').html();

    Index.prototype.initialize = function() {
      RepoList.agencies = new RepoList.Collections.Agencies;
      RepoList.agencies.fetch({
        update: true
      });
      return RepoList.agencies.on('add', this.render);
    };

    Index.prototype.render = function() {
      var html;
      html = '';
      _.each(RepoList.agencies, function(nil, i, agencies) {
        var view;
        view = new RepoList.Views.Agency({
          model: agencies.models[i]
        });
        return html += view.render();
      });
      return this.$el.html(html);
    };

    return Index;

  })(Backbone.View);

  RepoList.Views.Agency = (function(_super) {

    __extends(Agency, _super);

    function Agency() {
      return Agency.__super__.constructor.apply(this, arguments);
    }

    Agency.prototype.el = "#agencies";

    Agency.prototype.tagName = "li";

    Agency.prototype["class"] = "agency";

    Agency.prototype.template = $("#agency_template").html();

    Agency.prototype.render = function() {
      var compiled, repos;
      repos = '';
      _.each(this.model.get('repos', function(repo) {
        var view;
        view = new RepoList.Views.Repo({
          model: repo
        });
        return repos += view.render();
      }));
      compiled = _.template(this.template);
      return compiled({
        agency: this.model.toJSON(),
        repos: repos
      });
    };

    return Agency;

  })(Backbone.View);

  RepoList.Views.Repo = (function(_super) {

    __extends(Repo, _super);

    function Repo() {
      return Repo.__super__.constructor.apply(this, arguments);
    }

    Repo.prototype.el = ".repos";

    Repo.prototype.tagName = "li";

    Repo.prototype["class"] = "repo";

    Repo.prototype.template = $("#repo_template").html();

    Repo.prototype.render = function() {
      var compiled;
      compiled = _.template(this.template);
      return compiled(this.model.toJSON());
    };

    return Repo;

  })(Backbone.View);

  router = (function(_super) {

    __extends(router, _super);

    function router() {
      return router.__super__.constructor.apply(this, arguments);
    }

    router.prototype.routes = {
      "": "index"
    };

    router.prototype.index = function() {
      var view;
      return view = new RepoList.Views.Index();
    };

    return router;

  })(Backbone.Router);

  RepoList.router = new router();

  Backbone.history.start();

}).call(this);
